//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLS.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public Borrow()
        {
            this.Fine = new HashSet<Fine>();
        }
    
        public int Id { get; set; }
        public int RId { get; set; }
        public int BId { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public System.DateTime EdReturnDate { get; set; }
        public Nullable<bool> Renewal { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
        public virtual ICollection<Fine> Fine { get; set; }
    }
}
